/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include <vector>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1100508_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1100508_1[] = { "idle", "scrollDOWN", "scrollUP" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1100508_4_axes[] = { 0, 1, 2, 3, 4, 5 };
const uint32_t ei_dsp_config_1100508_4_axes_size = 6;
ei_dsp_config_flatten_t ei_dsp_config_1100508_4 = {
    4, // uint32_t blockId
    1, // int implementationVersion
    6, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_1100508_4[42] = { 5.5530314228600925, -3.6952221946169934, 15.963666632937061, 6.4713402749763596, 2.2113226571430764, 0.09251288526154693, 9.724367637352811, 0.5599656558906039, -5.427444430109527, 12.168777804573377, 6.724180461631881, 4.790131537947389, 0.2654854801586933, 2.1026898928814464, 0.2797081841621548, -2.7017777716120084, 3.4802222260998357, 1.7360384644733535, 0.7471978213638067, 0.28314473068522705, 10.41990797718366, -0.033621024912766494, -0.839333332868086, 0.39933333456930187, 0.13560002404782506, 0.12456286472475363, -1.4225943489646145, 19.705037986818287, -0.010501683597249211, -1.222222223919299, 0.9002222170432409, 0.1885663552313215, 0.1860084702571233, -0.8136174346139241, 20.216617574625545, 0.0016913588689122763, -2.029111046012905, 2.6712221283879547, 0.740493112626589, 0.706676465862741, 0.23845151993963454, 16.562228946884474 };
const float ei_dn_standard_scaler_scale_1100508_4[42] = { 0.33378874465495884, 0.09732331357257769, 0.08455133313619098, 0.43470101236091535, 0.63645650634232, 0.6581831618280074, 0.07699318720196209, 0.25385438656732895, 0.16062918956354397, 0.09259047584756258, 0.43814945107459574, 0.2930186541792224, 0.8033735430098441, 0.13680797520664015, 0.4550984537095444, 0.25368648393142323, 0.2642539891864762, 0.603434155118907, 1.8402302759128406, 0.5465862052253153, 0.059375862957027015, 23.276111270736436, 1.13272279015847, 2.1681847510482934, 9.873032447036602, 9.923798038963373, 0.30781007380765, 0.050167288048424775, 32.003873158805675, 0.7411073635566748, 0.8933178101859837, 6.479164461195194, 6.496709897851381, 0.33774972363507594, 0.05398531844444485, 4.231288468741943, 0.3382684092151808, 0.30144398890399327, 1.7751632228488232, 1.7948361273518756, 0.2562361132584246, 0.05735457176714071 };
const float ei_dn_standard_scaler_var_1100508_4[42] = { 8.975458095053007, 105.57624854122184, 139.88111351482132, 5.291986124300594, 2.468667155173697, 2.3083755450512013, 168.6923560939413, 15.517818047775204, 38.757081270707545, 116.64533316111064, 5.209013178003576, 11.646876258054478, 1.5494049868173871, 53.42901521018082, 4.82824478620588, 15.53836580998835, 14.32045759776607, 2.7462509725083684, 0.2952947031765214, 3.3472077354156, 283.64826454019607, 0.0018457766629273336, 0.7793862200330861, 0.21271956128837255, 0.01025885452580363, 0.0101541638132751, 10.55441925967172, 397.3367644900271, 0.000976326144059422, 1.8206972792489466, 1.2531065922236924, 0.02382110987828688, 0.023692617947090957, 8.766172155354731, 343.12207927110796, 0.055854057931144965, 8.739309457155652, 11.004916304287022, 0.31733897632876207, 0.3104205004354641, 15.230681061432938, 303.9932336006582 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1100508_4 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1100508_4,
    .mean_data_len = 42,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1100508_4,
    .scale_data_len = 42,
    .var_data = (float *)ei_dn_standard_scaler_var_1100508_4,
    .var_data_len = 42
};
ei_data_normalization_t ei_data_normalization_config_1100508_4 = {
    (void *) &ei_data_normalization_standard_scaler_config_1100508_4, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1100508_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1100508_1[ei_dsp_blocks_1100508_1_size] = {
    { // DSP block 4
        4,
        42, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_1100508_4, // pointer to config struct
        ei_dsp_config_1100508_4_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1100508_4_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_1100508_4, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1100508_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1100508_3_init,
    .model_invoke = &tflite_learn_1100508_3_invoke,
    .model_reset = &tflite_learn_1100508_3_reset,
    .model_input = &tflite_learn_1100508_3_input,
    .model_output = &tflite_learn_1100508_3_output,
};

const uint8_t ei_output_tensors_indices_1100508_3[1] = { 0 };
const uint8_t ei_output_tensors_size_1100508_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1100508_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_1100508_3,
    .output_tensors_size = ei_output_tensors_size_1100508_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1100508_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1100508_1_size = 1;
const uint32_t ei_learning_block_1100508_3_inputs[1] = { 4 };
const uint8_t ei_learning_block_1100508_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1100508_1[ei_learning_blocks_1100508_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1100508_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1100508_3_inputs,
        ei_learning_block_1100508_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1100508_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1100508_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1100508_1[ei_postprocessing_blocks_1100508_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1100508_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_1100508_1_size = 0;

uint32_t *freeform_outputs_1100508_1 = nullptr;

const ei_impulse_t impulse_1100508_1 = {
    .project_id = 1100508,
    .project_owner = "Anwiryani",
    .project_name = "IMUgestureEXP2",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 2,

    .nn_input_frame_size = 42,
    .raw_sample_count = 297,
    .raw_samples_per_frame = 6,
    .dsp_input_frame_size = 297 * 6,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 10,
    .frequency = 100,

    .dsp_blocks_size = ei_dsp_blocks_1100508_1_size,
    .dsp_blocks = ei_dsp_blocks_1100508_1,

    .learning_blocks_size = ei_learning_blocks_1100508_1_size,
    .learning_blocks = ei_learning_blocks_1100508_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1100508_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1100508_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "ax + ay + az + gx + gy + gz",
    .slice_size = (297/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_1100508_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1100508_1_size,
    .freeform_outputs = freeform_outputs_1100508_1
};

ei_impulse_handle_t impulse_handle_1100508_1 = ei_impulse_handle_t( &impulse_1100508_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1100508_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1100508_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1100508_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1100508_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
